baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'digital life'
[author]
  name = 'onielsen'
# config.toml
[params]
  google_analytics_id = ""
  twitter_handle = "@delirial"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#f5e960'
  baseColor = "#1e1e1e"
  baseOffsetColor = "#eaeaea"
  headingColor = "#e0e3e6"
  textColor = "#e0e3e6"
  dotColor = "#55d6c2"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"
  
[menu]
  [[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "why"
    identifier = "about"
    weight = 3
    url = "/about/"
    
[module]
[[module.imports]] 
  path = "github.com/hugo-mods/icons"
